name: flutter_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  easy_search_bar: ^2.4.2
  http: ^0.13.5
  pigeon: ^9.1.1
  provider: ^6.0.5
  shimmer: ^3.0.0
  fl_chart: ^0.62.0
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
flutter:

  uses-material-design: true
  
fonts:
    - family: CustomIconsFont
      fonts:
          - asset: assets/fonts/CustomIconsFont.ttf
    - family: ProximaNovaRegular
      fonts:
        - asset: assets/fonts/ProximaNova/ProximaNova-Regular.ttf
    - family: ProximaNovaSemibold
      fonts:
        - asset: assets/fonts/ProximaNova/ProximaNova-Semibold.ttf
    - family: ProximaNovaBold
      fonts:
        - asset: assets/fonts/ProximaNova/ProximaNova-Bold.ttf
    - family: ProximaNovaLight
      fonts:
        - asset: assets/fonts/ProximaNova/ProximaNova-Light.ttf