// Autogenerated from Pigeon (v9.1.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#import <Foundation/Foundation.h>

@protocol FlutterBinaryMessenger;
@protocol FlutterMessageCodec;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN

@class Stock;
@class StockInvest;
@class MyRequest;
@class MyResponse;

@interface Stock : NSObject
+ (instancetype)makeWithSymbol:(nullable NSString *)symbol
    name:(nullable NSString *)name
    price:(nullable NSNumber *)price
    date:(nullable NSString *)date
    change:(nullable NSNumber *)change
    percentChange:(nullable NSNumber *)percentChange;
@property(nonatomic, copy, nullable) NSString * symbol;
@property(nonatomic, copy, nullable) NSString * name;
@property(nonatomic, strong, nullable) NSNumber * price;
@property(nonatomic, copy, nullable) NSString * date;
@property(nonatomic, strong, nullable) NSNumber * change;
@property(nonatomic, strong, nullable) NSNumber * percentChange;
@end

@interface StockInvest : NSObject
+ (instancetype)makeWithSymbol:(nullable NSString *)symbol
    name:(nullable NSString *)name
    investedTotal:(nullable NSNumber *)investedTotal
    quantity:(nullable NSNumber *)quantity
    currentValue:(nullable NSNumber *)currentValue
    pl:(nullable NSNumber *)pl
    percentagePL:(nullable NSNumber *)percentagePL
    averagePrice:(nullable NSNumber *)averagePrice
    ltp:(nullable NSNumber *)ltp;
@property(nonatomic, copy, nullable) NSString * symbol;
@property(nonatomic, copy, nullable) NSString * name;
@property(nonatomic, strong, nullable) NSNumber * investedTotal;
@property(nonatomic, strong, nullable) NSNumber * quantity;
@property(nonatomic, strong, nullable) NSNumber * currentValue;
@property(nonatomic, strong, nullable) NSNumber * pl;
@property(nonatomic, strong, nullable) NSNumber * percentagePL;
@property(nonatomic, strong, nullable) NSNumber * averagePrice;
@property(nonatomic, strong, nullable) NSNumber * ltp;
@end

@interface MyRequest : NSObject
+ (instancetype)makeWithId:(nullable NSString *)id
    ticker:(nullable NSString *)ticker
    function:(nullable NSString *)function;
@property(nonatomic, copy, nullable) NSString * id;
@property(nonatomic, copy, nullable) NSString * ticker;
@property(nonatomic, copy, nullable) NSString * function;
@end

@interface MyResponse : NSObject
+ (instancetype)makeWithId:(nullable NSString *)id
    result:(nullable NSArray<Stock *> *)result;
@property(nonatomic, copy, nullable) NSString * id;
@property(nonatomic, strong, nullable) NSArray<Stock *> * result;
@end

/// The codec used by MyApi.
NSObject<FlutterMessageCodec> *MyApiGetCodec(void);

@protocol MyApi
- (void)getStocksInfoRequest:(MyRequest *)request completion:(void (^)(MyResponse *_Nullable, FlutterError *_Nullable))completion;
@end

extern void MyApiSetup(id<FlutterBinaryMessenger> binaryMessenger, NSObject<MyApi> *_Nullable api);

/// The codec used by StockApi.
NSObject<FlutterMessageCodec> *StockApiGetCodec(void);

@protocol StockApi
- (void)getStocksTicker:(NSString *)ticker function:(NSString *)function completion:(void (^)(NSArray<Stock *> *_Nullable, FlutterError *_Nullable))completion;
@end

extern void StockApiSetup(id<FlutterBinaryMessenger> binaryMessenger, NSObject<StockApi> *_Nullable api);

/// The codec used by StockInvestApi.
NSObject<FlutterMessageCodec> *StockInvestApiGetCodec(void);

@protocol StockInvestApi
- (void)getStocksInvestWithCompletion:(void (^)(NSArray<StockInvest *> *_Nullable, FlutterError *_Nullable))completion;
@end

extern void StockInvestApiSetup(id<FlutterBinaryMessenger> binaryMessenger, NSObject<StockInvestApi> *_Nullable api);

NS_ASSUME_NONNULL_END
